---
- name: downloading Jenkins Key
  apt_key: 
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: adding Jenkins repository
  apt_repository: 
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present

- name: installing Jenkins
  apt:
    package: jenkins
    state: present
    update_cache: yes
    autoclean: yes
    force: yes

- name: checking there is initialAdminPassword file
  stat:
    path: /var/lib/jenkins/secrets/initialAdminPassword
  register: initialAdminPassword

- name: copying initial admin password from server
  fetch:
    src: /var/lib/jenkins/secrets/initialAdminPassword
    dest: roles/jenkins/files/
    flat: yes
  when: initialAdminPassword.stat.exists == True

- name: configuring jenkins service
  systemd:
    name: jenkins
    daemon_reload: yes
    state: restarted
