---
- name: installing Packages
  apt:
    package: ["default-jdk", "tidy"]
    state: present
    update_cache: yes
    autoclean: yes
    force: yes

- name:
  import_tasks: roles/packages/tasks/eksctl.yml
