---
- name: installing Packages
  apt:
    package: ["default-jdk", "tidy"]
    state: present
    update_cache: yes
    autoclean: yes
    force: yes

- name: update Packages
  apt:
    package: ["git"]
    state: latest
    update_cache: yes
    autoclean: yes
    force: yes
