---
- name: installing python
  apt:
    name: ["curl", "python3", "python3-pip", "python3-distutils"]
    state: present
    update_cache: yes
    autoclean: yes
    force: yes

- name: installing aws cli
  command: "pip3 install awscli --upgrade"

- name: including /snap/bin to PATH environment variable
  lineinfile:
    path: /root/.bashrc
    line: 'PATH="$PATH:/snap/bin"'
    create: yes
